version: '3'

services:
  app:
    build:
      context: .
      args:
        - PORT=${APP_PORT}
    restart: always
    ports: 
      - ${APP_PORT}:80
    networks:
      - backend
networks:
  backend:
    external: true
